--liquibase formatted sql

-- ============================================================
-- 0. ESTENSIONI
-- ============================================================

--changeset cbiallo:001-enable-citext
CREATE EXTENSION IF NOT EXISTS citext;
--rollback DROP EXTENSION IF EXISTS citext;

-- ============================================================
-- 1. USERS
-- ============================================================

--changeset cbiallo:002-create-users
CREATE TABLE users (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    phone_number      VARCHAR(15)  UNIQUE,
    email             VARCHAR(255) UNIQUE,
    password_hash     VARCHAR(512) NOT NULL,
    date_of_birth     DATE         NOT NULL,
    is_email_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    is_phone_verified BOOLEAN      NOT NULL DEFAULT FALSE,
    last_login_at     TIMESTAMPTZ,
    created_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ, -- soft delete

    CONSTRAINT chk_users_contact CHECK (phone_number IS NOT NULL OR email IS NOT NULL)
);

CREATE INDEX idx_users_email ON users(email)        WHERE email        IS NOT NULL AND deleted_at IS NULL;
CREATE INDEX idx_users_phone ON users(phone_number) WHERE phone_number IS NOT NULL AND deleted_at IS NULL;
--rollback DROP TABLE users;

-- ============================================================
-- 2. PROFILES
-- ============================================================

--changeset cbiallo:003-create-profiles
CREATE TABLE profiles (
    id                BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id           BIGINT  NOT NULL UNIQUE,
    username          CITEXT  NOT NULL UNIQUE,
    full_name         VARCHAR(64),
    profile_image_url TEXT,
    bio               VARCHAR(150),
    website_url       TEXT,
    gender            TEXT    CHECK (gender IS NULL OR gender IN ('male','female','prefer_not_to_say','custom')),
    custom_gender     TEXT,
    is_private        BOOLEAN NOT NULL DEFAULT FALSE,
    is_verified       BOOLEAN NOT NULL DEFAULT FALSE,
    followers_count   INTEGER NOT NULL DEFAULT 0,
    following_count   INTEGER NOT NULL DEFAULT 0,
    posts_count       INTEGER NOT NULL DEFAULT 0,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at        TIMESTAMPTZ, -- soft delete

    CONSTRAINT chk_profiles_gender CHECK (
        (gender = 'custom' AND custom_gender IS NOT NULL)
        OR (gender IS DISTINCT FROM 'custom' AND custom_gender IS NULL)
    ),
    CONSTRAINT fk_profiles_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE INDEX idx_profiles_username ON profiles(username) WHERE deleted_at IS NULL;
CREATE INDEX idx_profiles_user_id  ON profiles(user_id)  WHERE deleted_at IS NULL;
--rollback DROP TABLE profiles;

-- ============================================================
-- 3. FOLLOWS
-- ============================================================

--changeset cbiallo:004-create-follows
CREATE TABLE follows (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    follower_profile_id  BIGINT NOT NULL,
    following_profile_id BIGINT NOT NULL,
    status               TEXT   NOT NULL DEFAULT 'accepted'
                                CHECK (status IN ('pending','accepted','rejected')),
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at           TIMESTAMPTZ, -- soft delete

    CONSTRAINT chk_follows_no_self CHECK (follower_profile_id != following_profile_id),
    CONSTRAINT fk_follows_follower  FOREIGN KEY (follower_profile_id)  REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_follows_following FOREIGN KEY (following_profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_follows_unique_active ON follows(follower_profile_id, following_profile_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_follows_follower  ON follows(follower_profile_id)  WHERE deleted_at IS NULL AND status = 'accepted';
CREATE INDEX idx_follows_following ON follows(following_profile_id) WHERE deleted_at IS NULL AND status = 'accepted';
CREATE INDEX idx_follows_pending   ON follows(following_profile_id) WHERE deleted_at IS NULL AND status = 'pending';
CREATE INDEX idx_follows_rejected  ON follows(following_profile_id) WHERE deleted_at IS NULL AND status = 'rejected';
--rollback DROP TABLE follows;

-- ============================================================
-- 4. POSTS
-- ============================================================

--changeset cbiallo:005-create-posts
CREATE TABLE posts (
    id                   BIGINT  GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id           BIGINT  NOT NULL,
    caption              VARCHAR(2200),
    location             TEXT,
    is_comments_disabled BOOLEAN NOT NULL DEFAULT FALSE,
    is_likes_hidden      BOOLEAN NOT NULL DEFAULT FALSE,
    likes_count          INTEGER NOT NULL DEFAULT 0,
    comments_count       INTEGER NOT NULL DEFAULT 0,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at           TIMESTAMPTZ, -- soft delete

    CONSTRAINT fk_posts_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_posts_profile ON posts(profile_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_posts_feed    ON posts(created_at DESC)             WHERE deleted_at IS NULL;
--rollback DROP TABLE posts;

-- ============================================================
-- 5. POST_MEDIA
-- ============================================================

--changeset cbiallo:006-create-post-media
CREATE TABLE post_media (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id          BIGINT NOT NULL,
    media_url        TEXT   NOT NULL,
    media_type       TEXT   NOT NULL CHECK (media_type IN ('image','video')),
    duration_seconds DOUBLE PRECISION,
    position         INTEGER NOT NULL,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at       TIMESTAMPTZ, -- soft delete

    CONSTRAINT fk_post_media_post FOREIGN KEY (post_id) REFERENCES posts(id) ON DELETE CASCADE,
    UNIQUE (post_id, position)
);

CREATE INDEX idx_post_media_post ON post_media(post_id, position) WHERE deleted_at IS NULL;
--rollback DROP TABLE post_media;

-- ============================================================
-- 6. POST_TAGS
-- ============================================================

--changeset cbiallo:007-create-post-tags
CREATE TABLE post_tags (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id           BIGINT NOT NULL,
    post_media_id     BIGINT,
    tagged_profile_id BIGINT NOT NULL,
    x_position        DOUBLE PRECISION,
    y_position        DOUBLE PRECISION,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_post_tags_post    FOREIGN KEY (post_id)           REFERENCES posts(id)      ON DELETE CASCADE,
    CONSTRAINT fk_post_tags_media   FOREIGN KEY (post_media_id)     REFERENCES post_media(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_tags_profile FOREIGN KEY (tagged_profile_id) REFERENCES profiles(id)   ON DELETE CASCADE,
    UNIQUE (post_id, post_media_id, tagged_profile_id)
);

CREATE INDEX idx_post_tags_post    ON post_tags(post_id);
CREATE INDEX idx_post_tags_profile ON post_tags(tagged_profile_id);
--rollback DROP TABLE post_tags;

-- ============================================================
-- 7. COMMENTS
-- ============================================================

--changeset cbiallo:008-create-comments
CREATE TABLE comments (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id     BIGINT       NOT NULL,
    profile_id  BIGINT       NOT NULL,
    parent_id   BIGINT,
    text        VARCHAR(2200) NOT NULL,
    likes_count INTEGER      NOT NULL DEFAULT 0,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ,
    deleted_at  TIMESTAMPTZ, -- soft delete

    CONSTRAINT fk_comments_post    FOREIGN KEY (post_id)    REFERENCES posts(id)     ON DELETE CASCADE,
    CONSTRAINT fk_comments_profile FOREIGN KEY (profile_id) REFERENCES profiles(id)  ON DELETE CASCADE,
    CONSTRAINT fk_comments_parent  FOREIGN KEY (parent_id)  REFERENCES comments(id)  ON DELETE CASCADE
);

CREATE INDEX idx_comments_post    ON comments(post_id, created_at) WHERE deleted_at IS NULL;
CREATE INDEX idx_comments_profile ON comments(profile_id)          WHERE deleted_at IS NULL;
CREATE INDEX idx_comments_parent  ON comments(parent_id)           WHERE parent_id IS NOT NULL AND deleted_at IS NULL;
--rollback DROP TABLE comments;

-- ============================================================
-- 8. STORIES
-- ============================================================

--changeset cbiallo:009-create-stories
CREATE TABLE stories (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id       BIGINT NOT NULL,
    media_url        TEXT   NOT NULL,
    media_type       TEXT   NOT NULL CHECK (media_type IN ('image','video')),
    duration_seconds DOUBLE PRECISION,
    views_count      INTEGER     NOT NULL DEFAULT 0,
    created_at       TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    expires_at       TIMESTAMPTZ NOT NULL,
    deleted_at       TIMESTAMPTZ, -- soft delete

    CONSTRAINT fk_stories_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_stories_profile ON stories(profile_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_stories_active  ON stories(profile_id, expires_at DESC) WHERE deleted_at IS NULL;
--rollback DROP TABLE stories;

-- ============================================================
-- 9. STORY_VIEWS
-- ============================================================

--changeset cbiallo:010-create-story-views
CREATE TABLE story_views (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    story_id          BIGINT NOT NULL,
    viewer_profile_id BIGINT NOT NULL,
    viewed_at         TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_story_views_story  FOREIGN KEY (story_id)          REFERENCES stories(id)  ON DELETE CASCADE,
    CONSTRAINT fk_story_views_viewer FOREIGN KEY (viewer_profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    UNIQUE (story_id, viewer_profile_id)
);

CREATE INDEX idx_story_views_story  ON story_views(story_id,  viewed_at DESC);
CREATE INDEX idx_story_views_viewer ON story_views(viewer_profile_id);
--rollback DROP TABLE story_views;

-- ============================================================
-- 10. LIKES
-- ============================================================

--changeset cbiallo:011-create-likes
CREATE TABLE likes (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id    BIGINT NOT NULL,
    likeable_type TEXT   NOT NULL CHECK (likeable_type IN ('post','comment','story')),
    likeable_id   BIGINT NOT NULL,
    created_at    TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at    TIMESTAMPTZ, -- soft delete

    CONSTRAINT fk_likes_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_likes_unique_active ON likes(profile_id, likeable_type, likeable_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_likes_profile             ON likes(profile_id)                              WHERE deleted_at IS NULL;
CREATE INDEX idx_likes_content             ON likes(likeable_type, likeable_id)              WHERE deleted_at IS NULL;
--rollback DROP TABLE likes;

-- ============================================================
-- 11. SAVED_POSTS
-- ============================================================

--changeset cbiallo:012-create-saved-posts
CREATE TABLE saved_posts (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    post_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ, -- soft delete

    CONSTRAINT fk_saved_posts_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_saved_posts_post    FOREIGN KEY (post_id)    REFERENCES posts(id)    ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_saved_posts_unique_active ON saved_posts(profile_id, post_id) WHERE deleted_at IS NULL;
CREATE INDEX idx_saved_posts_profile              ON saved_posts(profile_id)          WHERE deleted_at IS NULL;
CREATE INDEX idx_saved_posts_post                 ON saved_posts(post_id)             WHERE deleted_at IS NULL;
--rollback DROP TABLE saved_posts;

-- ============================================================
-- 12. CHATS
-- ============================================================

--changeset cbiallo:013-create-chats
CREATE TABLE chats (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    is_group              BOOLEAN     NOT NULL DEFAULT FALSE,
    name                  VARCHAR(100),
    created_by_profile_id BIGINT,
    last_message_at       TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at            TIMESTAMPTZ, -- soft delete

    CONSTRAINT fk_chats_creator FOREIGN KEY (created_by_profile_id) REFERENCES profiles(id) ON DELETE SET NULL
);

CREATE INDEX idx_chats_last_message ON chats(last_message_at DESC) WHERE deleted_at IS NULL;
--rollback DROP TABLE chats;

-- ============================================================
-- 13. MESSAGES  (prima di chat_participants per via della FK)
-- ============================================================

--changeset cbiallo:014-create-messages
CREATE TABLE messages (
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id           BIGINT NOT NULL,
    sender_profile_id BIGINT NOT NULL,
    text              TEXT   NOT NULL,
    created_at        TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at        TIMESTAMPTZ,
    deleted_at        TIMESTAMPTZ,

    CONSTRAINT fk_messages_chat   FOREIGN KEY (chat_id)           REFERENCES chats(id)    ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_profile_id) REFERENCES profiles(id) ON DELETE CASCADE
);

CREATE INDEX idx_messages_chat   ON messages(chat_id, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX idx_messages_sender ON messages(sender_profile_id)        WHERE deleted_at IS NULL;
--rollback DROP TABLE messages;

-- ============================================================
-- 14. CHAT_PARTICIPANTS  (dopo messages per la FK last_read_message_id)
-- ============================================================

--changeset cbiallo:015-create-chat-participants
CREATE TABLE chat_participants (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id              BIGINT  NOT NULL,
    profile_id           BIGINT  NOT NULL,
    role                 TEXT    NOT NULL DEFAULT 'member' CHECK (role IN ('admin','member')),
    is_muted             BOOLEAN NOT NULL DEFAULT FALSE,
    last_read_message_id BIGINT,
    joined_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    left_at              TIMESTAMPTZ,

    CONSTRAINT fk_cp_chat      FOREIGN KEY (chat_id)              REFERENCES chats(id)    ON DELETE CASCADE,
    CONSTRAINT fk_cp_profile   FOREIGN KEY (profile_id)           REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_cp_last_read FOREIGN KEY (last_read_message_id) REFERENCES messages(id) ON DELETE SET NULL
);

CREATE UNIQUE INDEX idx_cp_unique_active ON chat_participants(chat_id, profile_id) WHERE left_at IS NULL;
CREATE INDEX idx_cp_chat                 ON chat_participants(chat_id)             WHERE left_at IS NULL;
CREATE INDEX idx_cp_profile              ON chat_participants(profile_id)          WHERE left_at IS NULL;
--rollback DROP TABLE chat_participants;

-- ============================================================
-- 15. NOTIFICATIONS
-- ============================================================

--changeset cbiallo:016-create-notifications
CREATE TABLE notifications (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    recipient_profile_id BIGINT NOT NULL,
    sender_profile_id    BIGINT,
    type                 TEXT   NOT NULL CHECK (type IN (
                             'like_post','like_comment','like_story',
                             'comment','comment_reply',
                             'follow','follow_request','follow_accepted',
                             'mention_post','mention_comment','mention_story',
                             'tag','message','story_view'
                         )),
    reference_type       TEXT   CHECK (reference_type IS NULL OR reference_type IN ('post','comment','story','chat','profile')),
    reference_id         BIGINT,
    is_read              BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_notifications_recipient FOREIGN KEY (recipient_profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_notifications_sender    FOREIGN KEY (sender_profile_id)    REFERENCES profiles(id) ON DELETE SET NULL
);

CREATE INDEX idx_notifications_recipient ON notifications(recipient_profile_id, created_at DESC);
CREATE INDEX idx_notifications_unread    ON notifications(recipient_profile_id, is_read) WHERE is_read = FALSE;
--rollback DROP TABLE notifications;
