--liquibase formatted sql

-- ============================================================
-- Sostituisce la tabella likes polimorfica (likeable_type +
-- likeable_id senza FK) con tre tabelle tipizzate che
-- garantiscono integrità referenziale reale.
-- ============================================================

--changeset cbiallo:017-drop-likes
DROP TABLE likes;
-- Non è possibile un rollback automatico di un DROP TABLE.
-- Per ripristinare: applicare il rollback del changeset 011 dallo schema iniziale.
--rollback SELECT 'manual rollback required: recreate likes table from 001_initial_schema.sql changeset 011';

-- ============================================================
-- POST LIKES
-- ============================================================

--changeset cbiallo:018-create-post-likes
CREATE TABLE post_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    post_id    BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_post_likes_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_post_likes_post    FOREIGN KEY (post_id)    REFERENCES posts(id)    ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_post_likes_active  ON post_likes(profile_id, post_id) WHERE deleted_at IS NULL;
CREATE INDEX        idx_post_likes_profile ON post_likes(profile_id)          WHERE deleted_at IS NULL;
CREATE INDEX        idx_post_likes_post    ON post_likes(post_id)             WHERE deleted_at IS NULL;
--rollback DROP TABLE post_likes;

-- ============================================================
-- COMMENT LIKES
-- ============================================================

--changeset cbiallo:019-create-comment-likes
CREATE TABLE comment_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    comment_id BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_comment_likes_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_comment_likes_comment FOREIGN KEY (comment_id) REFERENCES comments(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_comment_likes_active  ON comment_likes(profile_id, comment_id) WHERE deleted_at IS NULL;
CREATE INDEX        idx_comment_likes_profile ON comment_likes(profile_id)             WHERE deleted_at IS NULL;
CREATE INDEX        idx_comment_likes_comment ON comment_likes(comment_id)             WHERE deleted_at IS NULL;
--rollback DROP TABLE comment_likes;

-- ============================================================
-- STORY LIKES
-- ============================================================

--changeset cbiallo:020-create-story-likes
CREATE TABLE story_likes (
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    profile_id BIGINT NOT NULL,
    story_id   BIGINT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,

    CONSTRAINT fk_story_likes_profile FOREIGN KEY (profile_id) REFERENCES profiles(id) ON DELETE CASCADE,
    CONSTRAINT fk_story_likes_story   FOREIGN KEY (story_id)   REFERENCES stories(id)  ON DELETE CASCADE
);

CREATE UNIQUE INDEX idx_story_likes_active  ON story_likes(profile_id, story_id) WHERE deleted_at IS NULL;
CREATE INDEX        idx_story_likes_profile ON story_likes(profile_id)           WHERE deleted_at IS NULL;
CREATE INDEX        idx_story_likes_story   ON story_likes(story_id)             WHERE deleted_at IS NULL;
--rollback DROP TABLE story_likes;

-- ============================================================
-- FIX: stories expires_at deve essere successivo a created_at
-- ============================================================

--changeset cbiallo:021-stories-expires-check
ALTER TABLE stories ADD CONSTRAINT chk_stories_expires CHECK (expires_at > created_at);
--rollback ALTER TABLE stories DROP CONSTRAINT chk_stories_expires;
