spring.application.name=service-discovery
server.port=8761

# Non si registra con se stesso
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# Disabilita il check di config server (non usa Config Server)
spring.cloud.config.import-check.enabled=false
